import = ["~/.config/alacritty/rose-pine.toml"]

[window]
padding = { x = 10, y = 10 }
decorations = "buttonless"
opacity = 0.85

[font]
size = 20

[font.normal]
family = "Iosevka NFM"
style = "Regular"
